/**
 * This is an autogenerated netlist code from CircuitVerse. Verilog Code can be
 * tested on https://www.edaplayground.com/ using Icarus Verilog 0.9.7. This is an
 * experimental module and some manual changes make need to be done in order for
 * this to work.
 *
 * If you have any ideas/suggestions or bug fixes, raise an issue
 * on https://github.com/CircuitVerse/CircuitVerse/issues/new/choose
 */

/*
  Element Usage Report
    Clock - 1 times
    DflipFlop - 8 times
    Output - 8 times
    Adder - 5 times
    Multiplexer - 11 times
    Demultiplexer - 1 times
    XorGate - 2 times
    OrGate - 9 times
    TwoComplement - 2 times
    Input - 6 times
    Decoder - 1 times
    Splitter - 1 times
*/

/*
  Usage Instructions and Tips
    Labels - Ensure unique label names and avoid using verilog keywords
    Warnings - Connect all optional inputs to remove warnings
    Clock - Use a single global clock
*/

// Sample Testbench Code - Uncomment to use

/*
module TestBench();

  reg Reset, Clock;
  reg [1:0] inp_3, inp_5;
  reg [3:0] Opcode_Input;
  reg [7:0] inp_0, inp_2;

  wire LED_Signal, Fire_Bullets_Signal;
  wire [1:0] Heading, LED_Color, Weapon_Type;
  wire [7:0] Speed, X_Position, Y_Position;

  Robot DUT0(Speed, Heading, LED_Color, LED_Signal, Fire_Bullets_Signal, X_Position, Y_Position, Weapon_Type, Clock, inp_0, Opcode_Input, inp_2, inp_3, Reset, inp_5);

  always begin
    #10
    Clock = 0;
    #10
    Clock = 1;
  end

  initial begin
    inp_0 = 0;
    Opcode_Input = 0;
    inp_2 = 0;
    inp_3 = 0;
    Reset = 0;
    inp_5 = 0;

    #15
    $display("Speed = %b", Speed);
    $display("Heading = %b", Heading);
    $display("LED_Color = %b", LED_Color);
    $display("LED_Signal = %b", LED_Signal);
    $display("Fire_Bullets_Signal = %b", Fire_Bullets_Signal);
    $display("X_Position = %b", X_Position);
    $display("Y_Position = %b", Y_Position);
    $display("Weapon_Type = %b", Weapon_Type);

    #10
    $display("Speed = %b", Speed);
    $display("Heading = %b", Heading);
    $display("LED_Color = %b", LED_Color);
    $display("LED_Signal = %b", LED_Signal);
    $display("Fire_Bullets_Signal = %b", Fire_Bullets_Signal);
    $display("X_Position = %b", X_Position);
    $display("Y_Position = %b", Y_Position);
    $display("Weapon_Type = %b", Weapon_Type);

    $finish;

  end
endmodule

*/

module Robot(Speed, Heading, LED_Color, LED_Signal, Fire_Bullets_Signal, X_Position, Y_Position, Weapon_Type, Clock, inp_0, Opcode_Input, inp_2, inp_3, Reset, inp_5);
  output LED_Signal,  Fire_Bullets_Signal;
  output [1:0] Heading, LED_Color, Weapon_Type;
  output [7:0] Speed, X_Position, Y_Position;
  input Reset, Clock;
  input [1:0] inp_3, inp_5;
  input [3:0] Opcode_Input;
  input [7:0] inp_0, inp_2;
  wire Fire_Bullets_Register_Q, Multiplexer_5_out, LED_Signal_Register_Q, Multiplexer_4_out, Demultiplexer_0_out_0, Demultiplexer_0_out_1, Demultiplexer_0_out_2, Demultiplexer_0_out_3, xor_1_out, or_7_out, xor_0_out, or_6_out, Decoder_0_out_0, Decoder_0_out_1, Decoder_0_out_2, Decoder_0_out_3, Decoder_0_out_4, Decoder_0_out_5, Decoder_0_out_6, Decoder_0_out_7, Decoder_0_out_8, Decoder_0_out_9, Decoder_0_out_10, Decoder_0_out_11, Decoder_0_out_12, or_8_out, or_5_out, or_4_out, or_3_out, or_1_out, or_2_out, or_0_out;
  wire [1:0] Weapon_Type_Register_Q, Adder_Sum, Multiplexer_10_out, LED_Color_Register_Q, Multiplexer_3_out, Heading_Register_Q, Multiplexer_2_out, Splitter_0_cmb;
  wire [7:0] Multiplexer_7_out, Adder_Sum, Multiplexer_8_out, X_Position_Register_Q, Multiplexer_6_out, Multiplexer_9_out, Y_Position_Register_Q, Speed_Register_Q, TwoComplement_0_\2's_complement , TwoComplement_1_\2's_complement , Multiplexer_0_out, Multiplexer_1_out;
  DflipFlop #(2) Weapon_Type_Register(Weapon_Type_Register_Q, , Clock, Multiplexer_10_out, Reset, , );
  assign Weapon_Type = Weapon_Type_Register_Q;
  assign Adder_Sum = Weapon_Type_Register_Q + inp_5;
  Multiplexer2 #(2) Multiplexer_10(Multiplexer_10_out, Weapon_Type_Register_Q, Adder_Sum, Decoder_0_out_12);
  DflipFlop Fire_Bullets_Register(Fire_Bullets_Register_Q, , Clock, Multiplexer_5_out, Reset, , );
  assign Fire_Bullets_Signal = Fire_Bullets_Register_Q;
  Multiplexer2 Multiplexer_5(Multiplexer_5_out, Fire_Bullets_Register_Q, Decoder_0_out_8, or_5_out);
  DflipFlop LED_Signal_Register(LED_Signal_Register_Q, , Clock, Multiplexer_4_out, Reset, , );
  assign LED_Signal = LED_Signal_Register_Q;
  Multiplexer2 Multiplexer_4(Multiplexer_4_out, LED_Signal_Register_Q, Decoder_0_out_6, or_4_out);
  DflipFlop #(2) LED_Color_Register(LED_Color_Register_Q, , Clock, Multiplexer_3_out, Reset, , );
  assign LED_Color = LED_Color_Register_Q;
  Multiplexer2 #(2) Multiplexer_3(Multiplexer_3_out, LED_Color_Register_Q, Splitter_0_cmb, or_3_out);
  DflipFlop #(2) Heading_Register(Heading_Register_Q, , Clock, Multiplexer_2_out, Reset, , );
  Demultiplexer4 Demultiplexer_0(Demultiplexer_0_out_0, Demultiplexer_0_out_1, Demultiplexer_0_out_2, Demultiplexer_0_out_3, or_8_out, Heading_Register_Q);
  assign xor_1_out = Demultiplexer_0_out_3 ^ Decoder_0_out_11;
  Multiplexer2 #(8) Multiplexer_7(Multiplexer_7_out, Speed_Register_Q, TwoComplement_1_\2's_complement , xor_1_out);
  assign Adder_Sum = Multiplexer_7_out + X_Position_Register_Q;
  Multiplexer2 #(8) Multiplexer_8(Multiplexer_8_out, X_Position_Register_Q, Adder_Sum, or_7_out);
  DflipFlop #(8) X_Position_Register(X_Position_Register_Q, , Clock, Multiplexer_8_out, Reset, , );
  assign X_Position = X_Position_Register_Q;
  assign or_7_out = Demultiplexer_0_out_1 | Demultiplexer_0_out_3;
  assign xor_0_out = Demultiplexer_0_out_2 ^ Decoder_0_out_11;
  Multiplexer2 #(8) Multiplexer_6(Multiplexer_6_out, Speed_Register_Q, TwoComplement_0_\2's_complement , xor_0_out);
  assign Adder_Sum = Y_Position_Register_Q + Multiplexer_6_out;
  Multiplexer2 #(8) Multiplexer_9(Multiplexer_9_out, Y_Position_Register_Q, Adder_Sum, or_6_out);
  DflipFlop #(8) Y_Position_Register(Y_Position_Register_Q, , Clock, Multiplexer_9_out, Reset, , );
  assign Y_Position = Y_Position_Register_Q;
  assign or_6_out = Demultiplexer_0_out_0 | Demultiplexer_0_out_2;
  Multiplexer2 #(2) Multiplexer_2(Multiplexer_2_out, Heading_Register_Q, Adder_Sum, Decoder_0_out_2);
  assign Adder_Sum = inp_3 + Heading_Register_Q;
  assign Heading = Heading_Register_Q;
  DflipFlop #(8) Speed_Register(Speed_Register_Q, , Clock, Multiplexer_0_out, Reset, , );
  assign Speed = Speed_Register_Q;
  assign TwoComplement_0_\2's_complement  = ~Speed_Register_Q + 1;
  assign TwoComplement_1_\2's_complement  = ~Speed_Register_Q + 1;
  assign Adder_Sum = Multiplexer_1_out + Speed_Register_Q;
  Multiplexer2 #(8) Multiplexer_0(Multiplexer_0_out, Speed_Register_Q, Adder_Sum, or_0_out);
  Multiplexer2 #(8) Multiplexer_1(Multiplexer_1_out, inp_0, inp_2, Decoder_0_out_1);
  Decoder16 #(4) Decoder_0(Decoder_0_out_0, Decoder_0_out_1, Decoder_0_out_2, Decoder_0_out_3, Decoder_0_out_4, Decoder_0_out_5, Decoder_0_out_6, Decoder_0_out_7, Decoder_0_out_8, Decoder_0_out_9, Decoder_0_out_10, Decoder_0_out_11, Decoder_0_out_12, , , , Opcode_Input);
  assign or_8_out = Decoder_0_out_10 | Decoder_0_out_11;
  assign or_5_out = Decoder_0_out_8 | Decoder_0_out_9;
  assign or_4_out = Decoder_0_out_6 | Decoder_0_out_7;
  assign or_3_out = Decoder_0_out_3 | Decoder_0_out_5 | Decoder_0_out_4 | Decoder_0_out_5;
  assign or_1_out = Decoder_0_out_3 | Decoder_0_out_5;
  assign Splitter_0_cmb = {or_2_out,or_1_out};
  assign or_2_out = Decoder_0_out_4 | Decoder_0_out_5;
  assign or_0_out = Decoder_0_out_0 | Decoder_0_out_1;
endmodule

module DflipFlop(q, q_inv, clk, d, a_rst, pre, en);
    parameter WIDTH = 1;
    output reg [WIDTH-1:0] q, q_inv;
    input clk, a_rst, pre, en;
    input [WIDTH-1:0] d;

    always @ (posedge clk or posedge a_rst)
    if (a_rst) begin
        q <= 'b0;
        q_inv <= 'b1;
    end else if (en == 0) ;
    else begin
        q <= d;
        q_inv <= ~d;
    end
endmodule
    
module Multiplexer2(out, in0, in1, sel);
  parameter WIDTH = 1;
  output reg [WIDTH-1:0] out;
  input [WIDTH-1:0] in0, in1;
  input [0:0] sel;
  
  always @ (*)
    case (sel)
      0 : out = in0;
      1 : out = in1;
    endcase
endmodule


module Demultiplexer4(out0, out1, out2, out3, in, sel);
  parameter WIDTH = 1;
  output reg [WIDTH-1:0] out0, out1, out2, out3;
  input [WIDTH-1:0] in;
  input [1:0] sel;
  
  always @ (*) begin
    out0 = 0;
    out1 = 0;
    out2 = 0;
    out3 = 0;
    case (sel)
      0 : out0 = in;
      1 : out1 = in;
      2 : out2 = in;
      3 : out3 = in;
    endcase
  end
endmodule

module Decoder16(out0, out1, out2, out3, out4, out5, out6, out7, out8, out9, out10, out11, out12, out13, out14, out15, sel);
  output reg out0, out1, out2, out3, out4, out5, out6, out7, out8, out9, out10, out11, out12, out13, out14, out15;
  input [3:0] sel;
  
  always @ (*) begin
    out0 = 0;
    out1 = 0;
    out2 = 0;
    out3 = 0;
    out4 = 0;
    out5 = 0;
    out6 = 0;
    out7 = 0;
    out8 = 0;
    out9 = 0;
    out10 = 0;
    out11 = 0;
    out12 = 0;
    out13 = 0;
    out14 = 0;
    out15 = 0;
    case (sel)
      0 : out0 = 1;
      1 : out1 = 1;
      2 : out2 = 1;
      3 : out3 = 1;
      4 : out4 = 1;
      5 : out5 = 1;
      6 : out6 = 1;
      7 : out7 = 1;
      8 : out8 = 1;
      9 : out9 = 1;
      10 : out10 = 1;
      11 : out11 = 1;
      12 : out12 = 1;
      13 : out13 = 1;
      14 : out14 = 1;
      15 : out15 = 1;
    endcase
  end
endmodule
